### ISSUE TITLE
hyper-parameter 문의

### ISSUE THREAD

**Issue by reniew** [monologg/KoBERT-nsmc#1]
안녕하세요!
혹시 readme에 작성된 성능은 main에있는 default  argument들을 넣어서 뽑은 성능인가요?

**Comment by monologg** [comment]
안녕하세요! 
- KoBert, DistilKoBert, mBert 3가지 모두 main.py 그대로 사용하였습니다. 
- 편의상 logging_step을 1000 단위로 하면서 test 결과가 제일 좋았던 것을 반영하였습니다. (dev set이 없는 관계로 training 동안 test set을 가지고 1000 step마다 evaluation하였습니다)
- Fasttext의 경우는 word 단위로 tokenize하여 [autotune](https://fasttext.cc/docs/en/autotune.html) 기능을 사용한 결과입니다.

**Comment by reniew** [comment]
답변감사합니다!
