### ISSUE TITLE
No such file or directory: 'model/training_args.bin'

### ISSUE THREAD

**Issue by gyunggyung** [monologg/KoBERT-nsmc#2]
```
FileNotFoundError: [Errno 2] No such file or directory: 'model\\training_args.bin'
```

학습을 한 경우 training_args.bin 가 없는 걸로 알고 있습니다!

![image](https://user-images.githubusercontent.com/26733242/78323069-a79a8300-75ab-11ea-9517-ed09445d8d97.png)

감사합니다.

**Comment by monologg** [comment]
이번에 args를 저장하는 파일명을 `training_config.bin`에서 `training_args.bin`으로 바꿨습니다.

그리고 이번에 아키텍쳐를 많이 바꿔서 새로 재학습을 하셔야 정상적으로 작동할 겁니다.

**Comment by gyunggyung** [comment]
그렇군요!! 답변 감사합니다.

2020년 4월 3일 (금) 오후 1:29, Jangwon Park <notifications@github.com>님이 작성:
