### ISSUE TITLE
kobert tokenizer 관한 질문

### ISSUE THREAD

**Issue by fightnyy** [monologg/KoBERT-nsmc#7]
안녕하세요 monologg님. HuggingFace에 올려주신 KoBERT 정말 잘 쓰고 있습니다. 감사합니다.
몇가지 질문드릴사항이 있어서 여쭤보고자 합니다.
1. KoBERT tokenizer의 default vocab size가 8002개로 확인했는데 혹시 해당 실험도 동일한 사이즈로 진행하신건가요?
2. 혹시 아니라면 monologg님이 생각하시는 최적의 vocab_size가 있을까요? 있다면 vocab_file도 공유가 가능하실까요?

**Comment by monologg** [comment]
1. 예 맞습니다! SKT에서 만든 KoBERT를 transformers 라이브러리에 맞게 포팅한 것이어서, 원래의 세팅도 그대로 유지되어 있습니다.
2. 이건 저의 개인적인 의견이지만 30000~40000 사이가 모델의 사이즈와 성능 등을 함께 고려할 때 적절하다고 생각합니다. `KoELECTRA`를 만들 때도 이러한 부분을 반영하여 제작했습니다. [vocab.txt](https://huggingface.co/monologg/koelectra-base-v3-discriminator/blob/main/vocab.txt)를 참고하시면 될 거 같습니다!

**Comment by fightnyy** [comment]
친절한 답변 정말 감사합니다!!
추가 질문을 드리자면
1. 그렇다면 혹시 tokenizer vocab_size 별로 성능 평가 하신 것도 있으실까요?
2. 그리고 KoBertTokenizer.from_pretrained("monologg/koelectra-base-v3-discriminator") 이렇게 사용하면 될까요?

**Comment by monologg** [comment]
1. 별도로 한 건 없습니다
2. 모델을 처음 Pretraining할때 사용한 Tokenizer를 사용해야만 정상적으로 결과가 나옵니다. 
예를 들어 이전 tokenizer에서는 idx=10에 `오늘` 이란 단어였는데, 새로운 tokenizer에서는 idx=10에 `과자` 라는 단어로 매핑되어 있으면 모델에서 인식할 때부터 꼬일껍니다.

KoELECTRA를 쓰려면 아래와 같이 써야만 원하는 결과가 나옵니다. 
![Screenshot_20210218-163116](https://user-images.githubusercontent.com/28896432/108320892-bc552900-7206-11eb-8737-c81ab4e6c815.png)

**Comment by monologg** [comment]
@fightnyy 
2번에 대해서는 근본적인 부분에서 착오가 있으신거 같습니다. embedding matrix 부분부터 시작해서 작동 방식 등등 확인해보시는게 좋을것 같습니다:)

**Comment by fightnyy** [comment]
"Electra"가  모델이름이었군요! 똑같이 KoBertTokenizer로 학습을 한 것인줄 알았습니다 ㅠㅠ
이제 완전히 이해가 되었습니다!!   친절한 답변 감사합니다!!  ☺️
